#ifndef AT32_ODRIVE_LED_PATTERN_H
#define AT32_ODRIVE_LED_PATTERN_H

#include <stdbool.h>
#include <stdint.h>

#include "axis.h"
#include "config.h"

/*
 * Status indication logic for the on-board WS2812B-2020 data line on PB2.
 *
 * This module is intentionally free of hardware dependencies (no CMSIS, no
 * registers, no g_axis): tests/Makefile compiles it on the host so the frame
 * encoding and the state/error -> colour mapping are verified without the board
 * in the loop.  status_led.c only feeds it a snapshot.
 */

/* ---------------------------------------------------------------------------
 * WS2812B-2020 frame encoding
 *
 * The bit stream is produced by TMR20_CH1 (PB2, GPIO_MUX2) in PWM mode with one
 * DMA transfer per bit: the compare value is reloaded every 1.25 us period, so
 * T0H/T1H are generated by hardware and no code ever runs with interrupts off
 * (the previous bit-banging driver held them off for ~90 us per frame, which
 * delayed the 24 kHz current loop and could drop UART bytes).
 *
 *   period 1.25 us : 360 ticks at the 288 MHz APB2 timer clock
 *   T0H    0.35 us : 100 ticks   (WS2812B window: 0.25..0.55 us)
 *   T1H    0.70 us : 201 ticks   (WS2812B window: 0.65..0.95 us)
 *   T0L    0.90 us, T1L 0.55 us   (both inside the WS2812B window)
 *
 * LED_WS2812_FRAME_ENTRIES entries are required: 24 colour bits plus one flush
 * slot.  The flush transfer raises the DMA transfer-complete flag right after
 * the last colour bit falls; the driver then stops the timer, which holds the
 * data line low for the reset/latch time (>= 50 us, in practice the whole
 * scheduler period).
 */
#define LED_WS2812_T0H_NS           (350u)
#define LED_WS2812_T1H_NS           (700u)
#define LED_WS2812_PERIOD_NS        (1250u)

/*
 * APB2 is divided by 2 on this board, so APB2 timers run at 2 * PCLK2.  TMR20
 * is an APB2 timer (see docs/pinout.md).
 */
#define LED_WS2812_TIMER_HZ         (BOARD_APB2_HZ * 2u)
#define LED_WS2812_NS_TO_TICKS(ns)  ((((LED_WS2812_TIMER_HZ) / 1000000u) * (ns)) / 1000u)

#define LED_WS2812_T0H_TICKS        LED_WS2812_NS_TO_TICKS(LED_WS2812_T0H_NS)
#define LED_WS2812_T1H_TICKS        LED_WS2812_NS_TO_TICKS(LED_WS2812_T1H_NS)
#define LED_WS2812_PERIOD_TICKS     LED_WS2812_NS_TO_TICKS(LED_WS2812_PERIOD_NS)

/* Timer period register value for one bit period. */
#define LED_WS2812_PERIOD_RELOAD    (LED_WS2812_PERIOD_TICKS - 1u)

#define LED_WS2812_FRAME_ENTRIES    (25u)

typedef struct
{
  uint8_t r;
  uint8_t g;
  uint8_t b;
} led_rgb_t;

/*
 * Fill 'frame' with LED_WS2812_FRAME_ENTRIES compare values for one WS2812
 * frame.  The WS2812 protocol is G-R-B, most significant bit first, and every
 * bit maps to its high-time in ticks (frame[0] is the first bit on the wire).
 * The trailing flush entry is always zero.
 */
void led_ws2812_encode(uint8_t r, uint8_t g, uint8_t b, uint32_t *frame);

/* Scale one 8-bit colour channel by an 8-bit brightness (round to nearest). */
static inline uint8_t led_scale_channel(uint8_t value, uint8_t brightness)
{
  return (uint8_t)((((uint32_t)value * (uint32_t)brightness) + 127u) / 255u);
}

/* ---------------------------------------------------------------------------
 * Status indication
 */

typedef enum
{
  LED_MODE_AUTO = 0,   /* colour/pattern follows the axis state (default) */
  LED_MODE_MANUAL = 1, /* constant colour, see led.color */
  LED_MODE_OFF = 2     /* always dark */
} led_mode_t;

/* Everything the indicator depends on, sampled by status_led.c. */
typedef struct
{
  uint32_t error;       /* axis error bitfield */
  int32_t state;        /* axis_state_t */
  bool calibrating;     /* startup / calibration sequence running */
  uint32_t time_ms;     /* monotonic clock, drives the blink phases */
} led_status_t;

/*
 * Error blink code: the index of the lowest set error bit plus one, so a host
 * that sees N red flashes knows which protection fired first:
 *
 *   1 invalid state            8 position limit
 *   2 bus over voltage         9 watchdog expired
 *   3 bus under voltage       10 calibration failed
 *   4 bus over current        11 emergency stop
 *   5 current limit           12 temperature sensor failed
 *   6 motor over temperature  13 (reserved for future bits)
 *   7 encoder failed
 *
 * 0 means "no error".
 */
#define LED_ERROR_BLINK_MAX         (13u)
uint8_t led_error_blink_code(uint32_t error);

/* Blink timings; deliberately slow enough for a 100 ms indicator task. */
#define LED_ERROR_ON_MS             (250u)
#define LED_ERROR_OFF_MS            (250u)
#define LED_ERROR_PAUSE_MS          (1500u)
#define LED_CALIBRATION_HALF_MS     (400u)

/*
 * Colour for the given status, already scaled by 'brightness' (0..255):
 *   error       red, 'code' flashes then a pause
 *   calibrating blue, 400 ms on / 400 ms off
 *   closed loop green, steady
 *   otherwise   blue, steady (idle / disarmed)
 */
led_rgb_t led_indicator_color(const led_status_t *status, uint8_t brightness);

/*
 * Bring-up self-test sequence: red, green, blue, white, dark, repeating every
 * 500 ms.  Used through the led.self_test parameter to check the whole chain
 * (encoder -> DMA -> waveform -> LED colour order) without a motor or a host
 * script; see docs/bringup.md.
 */
#define LED_SELF_TEST_STEP_MS       (500u)
#define LED_SELF_TEST_STEPS         (5u)
led_rgb_t led_self_test_color(uint32_t time_ms, uint8_t brightness);

#endif /* AT32_ODRIVE_LED_PATTERN_H */
