#ifndef AT32_ODRIVE_WS2812_H
#define AT32_ODRIVE_WS2812_H

#include <stdbool.h>
#include <stdint.h>

/*
 * WS2812B-2020 status LED driver (PB2).
 *
 * The waveform is generated by TMR20_CH1 + DMA1 channel 1: every 1.25 us timer
 * period the compare value is refreshed from a 25-entry frame, so sending a
 * frame costs a few register writes and never disables interrupts.  The bit
 * timing constants live in Inc/led_pattern.h.
 *
 * Usage:
 *   ws2812_init();
 *   if (ws2812_write(r, g, b)) { ...frame started... }
 *
 * ws2812_write() returns false while the previous frame is still on the wire
 * (about 31 us), in which case the caller simply retries on a later tick.
 */
void ws2812_init(void);
bool ws2812_write(uint8_t r, uint8_t g, uint8_t b);
bool ws2812_busy(void);

/*
 * Bring-up diagnostics (exposed as led.frames / led.frames_done):
 *   started   - frames handed to the timer/DMA
 *   completed - frames whose DMA transfer-complete interrupt fired
 *
 * If `started` keeps growing while `completed` stays behind (and ws2812_busy()
 * stays true), the timer/DMA chain is not producing the waveform; if they grow
 * together, the frame is on the wire and only the LED/wiring can be at fault.
 */
uint32_t ws2812_frames_started(void);
uint32_t ws2812_frames_completed(void);

#endif /* AT32_ODRIVE_WS2812_H */
